'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FalloutMonsterHunter.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arms() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arms", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cortez() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cortez", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cortez_Small160() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cortez_Small160", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property falloutMonsterHunterIntroCutscene() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("falloutMonsterHunterIntroCutscene", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property falloutMonsterHunterMainMenu1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("falloutMonsterHunterMainMenu1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fmhFightScene() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fmhFightScene", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fmhProtagonistHeadPNG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fmhProtagonistHeadPNG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fmhRaptor1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fmhRaptor1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fmhRaptorHead1_86Icon_NoGlow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fmhRaptorHead1_86Icon_NoGlow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fmhRaptorHead2_86Icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fmhRaptorHead2_86Icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fujiCity() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fujiCity", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itemRaptorBone1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itemRaptorBone1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itemRaptorBone1_InventorySmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itemRaptorBone1_InventorySmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itemRaptorBone2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itemRaptorBone2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itemRaptorBone3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itemRaptorBone3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itemRaptorClaws1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itemRaptorClaws1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itemRaptorClaws1_InventorySmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itemRaptorClaws1_InventorySmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itemRaptorClaws2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itemRaptorClaws2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itemRaptorClaws3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itemRaptorClaws3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itemRaptorHide1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itemRaptorHide1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itemRaptorHide1_InventorySmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itemRaptorHide1_InventorySmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itemRaptorHide2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itemRaptorHide2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itemRaptorHide3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itemRaptorHide3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itemRaptorSkull1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itemRaptorSkull1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itemRaptorSkull1_InventorySmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itemRaptorSkull1_InventorySmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itemRaptorSkull2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itemRaptorSkull2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itemRaptorSkull3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itemRaptorSkull3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itemRaptorTail1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itemRaptorTail1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itemRaptorTail1_InventorySmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itemRaptorTail1_InventorySmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itemRaptorTail2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itemRaptorTail2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property itemRaptorTail3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("itemRaptorTail3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mobRaptor1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mobRaptor1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mobRaptor2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mobRaptor2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Player() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Player", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Player_Shoeless() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Player_Shoeless", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Player_Shoeless_Small160() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Player_Shoeless_Small160", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Player_Small160() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Player_Small160", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pnlInventory() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pnlInventory", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorBoots1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorBoots1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorBoots1_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorBoots1_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorBoots1_Small160() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorBoots1_Small160", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorBoots1_Small72() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorBoots1_Small72", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorBoots2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorBoots2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorBoots2_Small160() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorBoots2_Small160", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorChestplate1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorChestplate1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorChestplate1_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorChestplate1_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorChestplate1_Small160() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorChestplate1_Small160", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorChestplate1_Small72() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorChestplate1_Small72", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorChestplate2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorChestplate2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorChestplate2_Small160() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorChestplate2_Small160", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorHelmet1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorHelmet1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorHelmet1_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorHelmet1_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorHelmet1_Small160() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorHelmet1_Small160", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorHelmet1_Small72() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorHelmet1_Small72", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorHelmet2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorHelmet2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorHelmet2_Small160() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorHelmet2_Small160", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorLeggings1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorLeggings1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorLeggings1_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorLeggings1_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorLeggings1_Small160() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorLeggings1_Small160", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorLeggings1_Small72() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorLeggings1_Small72", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorLeggings2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorLeggings2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorLeggings2_Small160() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorLeggings2_Small160", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorWeapon1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorWeapon1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorWeapon1_256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorWeapon1_256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorWeapon1_Small160() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorWeapon1_Small160", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorWeapon1_Small72() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorWeapon1_Small72", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorWeapon2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorWeapon2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property raptorWeapon2_Small160() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("raptorWeapon2_Small160", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property uziCartiBigBaller() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uziCartiBigBaller", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
